# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: PICAO Dashboard
# Description of the Site
description: Fast & reliable end-to-end certification, driven by connected processes and data, empowering people to build and sell sustainable cars that customers love.
# URL of Image of the Site
site-image: C:/Users/sfa/WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://cutewallpaper.org/21/automation-wallpaper/Live-Wallpaper-Tedpatrick.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: #thedevslot@gmail.com
facebook_username: #thedevslot
twitter_username: #thedevslot
instagram_username: #thedevslot
linkedin_username: #thedevslot
github_username:  #thedevslot
youtube_channel_id: #UCk_93NXYP-U_AOB5GfWlOow
reddit_username: #/
behance_username: #/
dribbble_username: #/
spotify_username: #/

# Google Analytics
google-analytics: #UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: TheDevsLot
# URL for the Image of the Author
author-image: #https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: The dashboard is intended to give you a quick overview about the PICAO Program Structure and the current progress. Starting off with the „General“ subpage in which the working structure of PICAO is described by using terms of the agile framework. These terms are defined for a better overall understanding and linked to the corresponding subpages for more detailed information.

Strategic Themes
The Strategic Themes provide an orientation, which reflect the strategic goal of the PICAO program. They are business objectives that are connecting a portfolio to the strategy of the enterprise. The ST influence portfolio strategy as well as portfolio decisions. In our case, there are 15 themes defined plus an additional “pot” for topics which could not be assigned to any of the given themes. These ST are defined and located in a JIRA project which is described in the next section.

Portfolio Epics
Epics in general are a container for a significant solution development initiative that captures the more substantial investments that occur within a portfolio. Additionally, Epics often require a definition of an MVP (Minimum Viable Product). In the PICAO Program the so called “Portfolio Epics” are established to a corresponding product, providing a defined scope and impact on an assigned ST. That is, multiple Portfolio Epics can be assigned to one ST. Currently there are more than 80 Portfolio Epics in total in the PICAO Program which are located in a JIRA Project alongside with the ST. This project is called “PICAO Program” in JIRA and contains information like the description, any given dependencies or the progress of the Portfolio Epic providing an overall progress estimation of the ST.

Product Epics
One stage below the Portfolio Epics there are the Product Epics., which always are referring to one specific product in the program. The Product Epics are bridging the gap between the more generic defined Portfolio Epics and the more operative tasks done by the agile teams. Therefore, the Product Epics are a detailed description of a Portfolio Epic, corresponding to one product. Since the dashboard and the PICAO program is still transforming, not all of the Product Epics can be shown here. Furthermore the current Product Epics are being linked to the superordinate Portfolio Epics to get a more realistic and instantaneous view of the progress.

Structure of the Strategic Theme

Link: https://gsep.daimler.com/jira/secure/StructureBoard.jspa?p=717892662


# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: #https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
